/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Article = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'language' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const CropPrice = IDL.Record({
  'date' : Time,
  'pricePerKg' : IDL.Float64,
  'marketLocation' : IDL.Text,
  'cropName' : IDL.Text,
  'trendUp' : IDL.Bool,
});
export const WeatherForecast = IDL.Record({
  'region' : IDL.Text,
  'temperature' : IDL.Int,
  'farmingTip' : IDL.Text,
  'humidity' : IDL.Int,
  'forecastDate' : Time,
  'rainfall' : IDL.Int,
});
export const FertilizerTask = IDL.Record({
  'fertilizerName' : IDL.Text,
  'dayOffset' : IDL.Int,
  'notes' : IDL.Text,
  'amount' : IDL.Text,
});
export const FertilizerSchedule = IDL.Record({
  'tasks' : IDL.Vec(FertilizerTask),
  'plantingDate' : IDL.Text,
  'cropType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addArticle' : IDL.Func([Article], [], []),
  'addCropPrice' : IDL.Func([CropPrice], [], []),
  'addFertilizerSchedule' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addWeatherForecast' : IDL.Func([WeatherForecast], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllPrices' : IDL.Func([], [IDL.Vec(CropPrice)], ['query']),
  'getArticlesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'getArticlesByLanguage' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'getMySchedule' : IDL.Func([], [FertilizerSchedule], ['query']),
  'getPricesByCrop' : IDL.Func([IDL.Text], [IDL.Vec(CropPrice)], ['query']),
  'getWeatherByRegion' : IDL.Func([IDL.Text], [WeatherForecast], ['query']),
  'initializeKnowledgeData' : IDL.Func([], [], []),
  'initializeMarketData' : IDL.Func([], [], []),
  'initializeWeatherData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Article = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'language' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const CropPrice = IDL.Record({
    'date' : Time,
    'pricePerKg' : IDL.Float64,
    'marketLocation' : IDL.Text,
    'cropName' : IDL.Text,
    'trendUp' : IDL.Bool,
  });
  const WeatherForecast = IDL.Record({
    'region' : IDL.Text,
    'temperature' : IDL.Int,
    'farmingTip' : IDL.Text,
    'humidity' : IDL.Int,
    'forecastDate' : Time,
    'rainfall' : IDL.Int,
  });
  const FertilizerTask = IDL.Record({
    'fertilizerName' : IDL.Text,
    'dayOffset' : IDL.Int,
    'notes' : IDL.Text,
    'amount' : IDL.Text,
  });
  const FertilizerSchedule = IDL.Record({
    'tasks' : IDL.Vec(FertilizerTask),
    'plantingDate' : IDL.Text,
    'cropType' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addArticle' : IDL.Func([Article], [], []),
    'addCropPrice' : IDL.Func([CropPrice], [], []),
    'addFertilizerSchedule' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addWeatherForecast' : IDL.Func([WeatherForecast], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllPrices' : IDL.Func([], [IDL.Vec(CropPrice)], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getArticlesByLanguage' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getMySchedule' : IDL.Func([], [FertilizerSchedule], ['query']),
    'getPricesByCrop' : IDL.Func([IDL.Text], [IDL.Vec(CropPrice)], ['query']),
    'getWeatherByRegion' : IDL.Func([IDL.Text], [WeatherForecast], ['query']),
    'initializeKnowledgeData' : IDL.Func([], [], []),
    'initializeMarketData' : IDL.Func([], [], []),
    'initializeWeatherData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };