/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'title' : string,
  'content' : string,
  'language' : string,
  'category' : string,
}
export interface CropPrice {
  'date' : Time,
  'pricePerKg' : number,
  'marketLocation' : string,
  'cropName' : string,
  'trendUp' : boolean,
}
export interface FertilizerSchedule {
  'tasks' : Array<FertilizerTask>,
  'plantingDate' : string,
  'cropType' : string,
}
export interface FertilizerTask {
  'fertilizerName' : string,
  'dayOffset' : bigint,
  'notes' : string,
  'amount' : string,
}
export type Time = bigint;
export interface WeatherForecast {
  'region' : string,
  'temperature' : bigint,
  'farmingTip' : string,
  'humidity' : bigint,
  'forecastDate' : Time,
  'rainfall' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addArticle' : ActorMethod<[Article], undefined>,
  'addCropPrice' : ActorMethod<[CropPrice], undefined>,
  'addFertilizerSchedule' : ActorMethod<[string, string], undefined>,
  'addWeatherForecast' : ActorMethod<[WeatherForecast], undefined>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllPrices' : ActorMethod<[], Array<CropPrice>>,
  'getArticlesByCategory' : ActorMethod<[string], Array<Article>>,
  'getArticlesByLanguage' : ActorMethod<[string], Array<Article>>,
  'getMySchedule' : ActorMethod<[], FertilizerSchedule>,
  'getPricesByCrop' : ActorMethod<[string], Array<CropPrice>>,
  'getWeatherByRegion' : ActorMethod<[string], WeatherForecast>,
  'initializeKnowledgeData' : ActorMethod<[], undefined>,
  'initializeMarketData' : ActorMethod<[], undefined>,
  'initializeWeatherData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];